# Configuração do Banco de Dados PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/workat_db
spring.datasource.username=postgres
spring.datasource.password=1234##

# Configuração do Hibernate/JPA
# Para desenvolvimento: 'update' cria/atualiza o schema. Mudar para 'validate' em produção.
spring.jpa.hibernate.ddl-auto=update
# Mostra as queries SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do Servidor
server.port=8080

# Configuração básica de JWT
jwt.secret=uma_chave_secreta_muito_forte_e_longa_para_ambiente_prod
jwt.expiration-ms=86400000